---
name: "Pull Request"
title: "[BBC-XXXX] Pull Request Title"
labels: "feature-request, not-reviewed"
assignees: "@blablacar/spa"
---

## Description

<!-- Give some context of this PR. Illustrate with screenshots or a video (gif, loom, etc.) -->

## What has been done

<!-- How do you solve the problem? -->

## Things to consider

<!-- Explain your changes. What are you expecting for the reviewers?  -->

## How was it was tested

<!--  Local environment with ui-library only, integrated within the main project, on which browsers, etc.   -->
